### ISSUE TITLE
Fault -32700: 'parse error. not well formed'

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/ipy2wp#10]
I'm getting this error while trying to publish a notebook:

```
/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
Traceback (most recent call last):
  File "../../ipy2wp/ipy2wp/ipy2wp.py", line 131, in <module>
    status_published)
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 1091, in __call__
    return self.__send(self.__name, args)
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 1431, in __request
    verbose=self.__verbose
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 1133, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 1149, in single_request
    return self.parse_response(resp)
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 1321, in parse_response
    return u.close()
  File "/home/juanlu/.miniconda3/envs/planet9/lib/python3.5/xmlrpc/client.py", line 654, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32700: 'parse error. not well formed'>
```

These are my packages:

```
└[20:46:29] $ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
└[20:51:37] $ jupyter --version
4.0.6
└[20:51:44] $ jupyter notebook --version
4.1.0
```

**Comment by kikocorreoso** [comment]
I would try to have a look on this asap but, in general, i stopped any development on the notebook/Jupyter stuff as their code/API is quite unstable and each new small version break some of my extensions... :-(

**Comment by Juanlu001** [comment]
No hurries, I totally understand. I will use an iframe inside the wordpress article in the meanwhile :)

**Comment by Juanlu001** [comment]
I have identified the problem in the figures that result of using `%matplotlib notebook`. I will rename the issue and leave it open - for the moment, I switched to `%matplotlib inline` instead.

**Comment by Juanlu001** [comment]
BTW there are some updates in my branch https://github.com/Juanlu001/ipy2wp/tree/update-jl. I intend to fix #12 and #13 there but don't have an ETA. I got rid of Python 2 support and the JS extension, but still I can make a pull request if you wish.

**Comment by kikocorreoso** [comment]
I haven't seen this until today. I will borrow some of the code from your branch. In fact, I already did some refactoring [here](https://github.com/Pybonacci/jupy2wp) without knowing the commits in your branch :-(

**Comment by astrojuanlu** [comment]
Oops, don't worry! Glad you're back to work :) I cannot dedicate much time to jupy2py but if there are easy issues that you want to assign me please go ahead!
